Fix : order by aggregate function
thecodingmachine/magic-query pull request #37
Opened 2017-06-05 15:28 UTC by dsavina

Ordering by the result of an aggregate function (`SUM`, `COUNT`, `MAX`, etc) was not supported., therefore only default `ASC` was available.

Error previously logged:

```
MagicQuery - NodeFactory: Unexpected parameters in aggregate function: array (
  'direction' => 'DESC',
)
```

2017-06-06 11:51 UTC, dsavina commented
All checks OK since 23ec40516c0b0c010adc7a430e3da0139ad6232e ( **[tests] use phpunit from dependencies instead of global install** )

2017-06-15 09:50 UTC, moufmouf requested changes

2017-06-15 09:50 UTC, moufmouf commented on tests/Mouf/Database/MagicQueryTest.php
> +            'driver' => $GLOBALS['db_driver'],
You introduce a "db_port" variable in phpunit.xml.dist, but you don't use it here.
Apart for this single change, I'm :+1: for merging this!

Thanks a lot

2017-06-15 12:44 UTC, dsavina commented on tests/Mouf/Database/MagicQueryTest.php
> +            'driver' => $GLOBALS['db_driver'],
Done!

2017-06-15 12:54 UTC, merged